### ISSUE TITLE
鸣笛接口建议接入

### ISSUE THREAD

**Issue by anysoft** [louliangsheng/hellobike#2]
https://a.hellobike.com/evehicle/api?rent.order.bell

{
    "action": "rent.order.bell",
    "ticket": "xxxxxx",
    "token": "xxxx",
    "bikeNo": "xxxx"
}

这个是鸣笛接口，调用后车辆会鸣笛几声

**Comment by louliangsheng** [comment]
已添加鸣笛按钮
