### ISSUE TITLE
设防和解防

### ISSUE THREAD

**Issue by anysoft** [louliangsheng/hellobike#3]
没想到大佬在线 哈哈
这个也加上吧，

设防
https://a.hellobike.com/evehicle/api?rent.order.setUpDefence
{
    "action": "rent.order.setUpDefence",
    "maction": "SET_DEFENCE",
    "bikeNo": "xxxxx",
    "token": "xxxxx"
}
解防
https://a.hellobike.com/evehicle/api?rent.order.withdrawDefence
{
    "action": "rent.order.withdrawDefence",
    "maction": "WITHDRAW_DEFENCE",
    "bikeNo": "xxxxx",
    "token": "xxxxx"
}

状态位在rent.order.getRentBikeStatus接口的 defenceStatus

**Comment by louliangsheng** [comment]
我其实不是啥大佬，我还在等真正大佬写个正式插件，这个设防和解防仿照开关车写一个就行。
